name: portal_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.1
  icons_launcher: ^1.1.7

flutter_icons:
  image_path: 'ressources/images/icon.png'
  ios: true
  android: true

flutter_app_name:
  name: "Les Voyageurs Gourmands"


flutter:
  # Configuration for Flutter-specific settings
  assets:
    - ressources/images/logoSite.png
  uses-material-design: true

  # Other Flutter configurations...
